version: "3.8"

networks:
  praxkitnet:
    name: praxkitnet

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
      
  app:
    container_name: "praxkit"
    depends_on: db
    volumes:
      - .:/var/www/html
    networks:
      - praxkitnet


  db:
    container_name: "praxkitdb"
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my-postgres-data
        target: /var/lib/postgresql12/data
        volume:
          nocopy: true
    networks:
      - praxkitnet
volumes:
  my-postgres-data: # named volumes can be managed easier using docker-compose
  deps:
  build:
