version: "3.8"

networks:
  praxkitnet:
    name: praxkitnet

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginxserv
    depends_on:
      - db
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - praxkitnet
      
  app:
    build: 
      context: ./praxkit
      dockerfile: ./phx.dockerfile
    container_name: "praxkit"
    depends_on: 
      - db
    ports:
      - 4000:4000
    volumes:
      - ./praxkit:/opt/app
    networks:
      - praxkitnet


  db:
    container_name: "praxkitdb"
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my-postgres-data
        target: /var/lib/postgresql12/data
        volume:
          nocopy: true
    networks:
      - praxkitnet
volumes:
  my-postgres-data: # named volumes can be managed easier using docker-compose

