version: "3.5"
services:
  db:
    container_name: "praxkit_postgres"
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: my-postgres-data
        target: /var/lib/postgresql12/data
        volume:
          nocopy: true
volumes:
  my-postgres-data: # named volumes can be managed easier using docker-compose
  deps:
  build:
