# fly.toml file generated for praxkit-stage on 2021-10-19T18:15:09+02:00

app = "praxkit-stage"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[deploy]
  release_command = "/app/bin/praxkit eval Praxkit.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
