version: "3.5"
services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: "praxkit_local_postgres"
    image: postgres:14-alpine3.14
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  postgres-data:

